# Generated by Django 5.0.1 on 2024-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='clients',
            field=models.CharField(default='client-default', max_length=50),
        ),
    ]
