# Generated by Django 5.0.1 on 2024-01-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0002_production_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='clients',
            new_name='client',
        ),
    ]
