# Generated by Django 5.0.1 on 2024-01-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0003_rename_clients_production_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='producers',
            field=models.ManyToManyField(related_name='prods', to='BASE.producer'),
        ),
    ]
