# Generated by Django 5.0.1 on 2024-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0004_producer_production_producers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('LIGHT', 'lighting'), ('ANIM', 'animation'), ('MODEL', 'modelling'), ('SURFACE', 'surfacing'), ('FX', 'fx'), ('RIG', 'rigging')], max_length=50)),
            ],
        ),
    ]
