# Generated by Django 5.0.1 on 2024-01-17 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
