# Generated by Django 5.0.1 on 2024-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0006_task_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateDue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateCreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
