# Generated by Django 5.0.1 on 2024-01-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0009_supervisor_alter_task_producerid_task_supervisorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='producerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producerTasks', to='BASE.producer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supervisorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisorTasks', to='BASE.supervisor'),
        ),
    ]
