# Generated by Django 5.0.1 on 2024-01-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0011_alter_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CgArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('LIGHT', 'lighting'), ('COMP', 'compositing'), ('ANIM', 'animation'), ('MODEL', 'modelling'), ('SURFACE', 'surfacing'), ('FX', 'fx'), ('RIG', 'rigging')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='cgArtistId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cgArtistTasks', to='BASE.supervisor'),
        ),
    ]
