# Generated by Django 5.0.1 on 2024-01-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0012_cgartist_task_cgartistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='PRODUCTIONId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PRODUCTIONTasks', to='BASE.production'),
        ),
    ]
