# Generated by Django 5.0.1 on 2024-01-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0013_task_productionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cgArtistId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cgArtistTasks', to='BASE.cgartist'),
        ),
    ]
